dump_dts: Opening dtb file in binary mode
Opening dtb in text mode and writing raw binary
had introduced CR (\r) for every LF (\n) in the
binary. This has caused dtc to fail when trying
to convert dtb into dts in Windows environment.

Python on Windows has distinction between text
and binary files. DTB file should be opened in
binary mode to write the raw binary data.

Error:
FATAL ERROR: Invalid opcode word 0d0a0000 in device tree blob

Change-Id: I698e115f2467995eb6e0240da5ff5a188e299847
Signed-off-by: Gokul Sriram Palanisamy <gokulsri@codeaurora.org>